name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node | ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=${echo $GITHUB_SHA | head -c7}
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t project-ci-api:${{ steps.generate_tag.outputs.sha }} .

      # - name: Push docker image
      #   run: docker push project-ci-api:latest
